create table diet_profiles (
    user_id         uuid        primary key,
    life_stage      varchar(32) not null default 'none',
    hide_disliked   boolean     not null default false,
    max_calories    integer,
    min_protein     integer,
    max_carbs       integer,
    max_fat         integer,
    min_fiber       integer,
    max_minutes     integer,
    target_calories integer,
    target_protein  integer,
    target_carbs    integer,
    target_fat      integer,
    updated_at      timestamp with time zone not null default current_timestamp,
    constraint ck_diet_profiles_life_stage check (life_stage in
        ('none', 'pregnancy', 'breastfeeding', 'older-adult', 'weakened-immunity', 'post-surgery', 'burn-recovery'))
);

create table profile_restrictions (
    user_id     uuid        not null references diet_profiles (user_id) on delete cascade,
    restriction varchar(32) not null,
    primary key (user_id, restriction),
    constraint ck_profile_restrictions check (restriction in
        ('halal', 'kosher', 'vegan', 'vegetarian', 'pescatarian', 'gluten-free'))
);

create table profile_allergens (
    user_id  uuid        not null references diet_profiles (user_id) on delete cascade,
    allergen varchar(32) not null,
    primary key (user_id, allergen),
    constraint ck_profile_allergens check (allergen in
        ('milk', 'egg', 'fish', 'shellfish', 'tree-nuts', 'peanuts', 'wheat', 'soy', 'sesame'))
);

create table profile_dislikes (
    user_id uuid        not null references diet_profiles (user_id) on delete cascade,
    term    varchar(40) not null,
    primary key (user_id, term)
);

create table favorite_recipes (
    user_id    uuid        not null,
    recipe_id  varchar(80) not null,
    created_at timestamp with time zone not null default current_timestamp,
    primary key (user_id, recipe_id)
);

create table meal_log_entries (
    id                bigint generated by default as identity primary key,
    user_id           uuid          not null,
    eaten_on          date          not null,
    meal_type         varchar(16)   not null,
    recipe_id         varchar(80)   not null,
    recipe_name       varchar(200)  not null,
    servings          numeric(5, 2) not null,
    swaps             varchar(4000) not null default '[]',
    calories          numeric(8, 1) not null,
    protein           numeric(7, 1) not null,
    carbs             numeric(7, 1) not null,
    fat               numeric(7, 1) not null,
    fiber             numeric(7, 1) not null,
    nutrition_source  varchar(200)  not null,
    created_at        timestamp with time zone not null default current_timestamp,
    constraint ck_meal_log_meal_type check (meal_type in ('breakfast', 'lunch', 'dinner', 'snack')),
    constraint ck_meal_log_servings check (servings > 0 and servings <= 20)
);

create index ix_meal_log_user_date on meal_log_entries (user_id, eaten_on);

create table substitution_audit (
    id              bigint generated by default as identity primary key,
    user_id         uuid           not null,
    recipe_id       varchar(80)    not null,
    ingredient_id   varchar(80)    not null,
    reason          varchar(32)    not null,
    proposals       varchar(20000) not null,
    accepted_count  integer        not null,
    rejected_count  integer        not null,
    created_at      timestamp with time zone not null default current_timestamp
);

create index ix_substitution_audit_created on substitution_audit (created_at);
